import { Organization } from '@/types';

export const organizationsData: Omit<Organization, 'id'>[] = [
  // 中央
  {
    name: '中央',
    role: 'central',
    active: true,
    displayOrder: 0
  },
  
  // ブロック (9組織)
  { name: '北海道ブロック', role: 'block', active: true, displayOrder: 1 },
  { name: '東北ブロック', role: 'block', active: true, displayOrder: 2 },
  { name: '関東ブロック', role: 'block', active: true, displayOrder: 3 },
  { name: '北陸ブロック', role: 'block', active: true, displayOrder: 4 },
  { name: '東海ブロック', role: 'block', active: true, displayOrder: 5 },
  { name: '近畿ブロック', role: 'block', active: true, displayOrder: 6 },
  { name: '中国ブロック', role: 'block', active: true, displayOrder: 7 },
  { name: '四国ブロック', role: 'block', active: true, displayOrder: 8 },
  { name: '九州ブロック', role: 'block', active: true, displayOrder: 9 },
  
  // 分会 (52組織, displayOrder: 10-61)
  { name: '北海道', role: 'sub', active: true, displayOrder: 10 },
  { name: '青森', role: 'sub', active: true, displayOrder: 11 },
  { name: '岩手', role: 'sub', active: true, displayOrder: 12 },
  { name: '宮城', role: 'sub', active: true, displayOrder: 13 },
  { name: '秋田', role: 'sub', active: true, displayOrder: 14 },
  { name: '山形', role: 'sub', active: true, displayOrder: 15 },
  { name: '福島', role: 'sub', active: true, displayOrder: 16 },
  { name: '茨城', role: 'sub', active: true, displayOrder: 17 },
  { name: '栃木', role: 'sub', active: true, displayOrder: 18 },
  { name: '群馬', role: 'sub', active: true, displayOrder: 19 },
  { name: '埼玉', role: 'sub', active: true, displayOrder: 20 },
  { name: '千葉', role: 'sub', active: true, displayOrder: 21 },
  { name: '東京', role: 'sub', active: true, displayOrder: 22 },
  { name: '神奈川', role: 'sub', active: true, displayOrder: 23 },
  { name: '新潟', role: 'sub', active: true, displayOrder: 24 },
  { name: '富山', role: 'sub', active: true, displayOrder: 25 },
  { name: '石川', role: 'sub', active: true, displayOrder: 26 },
  { name: '福井', role: 'sub', active: true, displayOrder: 27 },
  { name: '山梨', role: 'sub', active: true, displayOrder: 28 },
  { name: '長野', role: 'sub', active: true, displayOrder: 29 },
  { name: '岐阜', role: 'sub', active: true, displayOrder: 30 },
  { name: '静岡', role: 'sub', active: true, displayOrder: 31 },
  { name: '愛知', role: 'sub', active: true, displayOrder: 32 },
  { name: '三重', role: 'sub', active: true, displayOrder: 33 },
  { name: '滋賀', role: 'sub', active: true, displayOrder: 34 },
  { name: '京都', role: 'sub', active: true, displayOrder: 35 },
  { name: '大阪', role: 'sub', active: true, displayOrder: 36 },
  { name: '兵庫', role: 'sub', active: true, displayOrder: 37 },
  { name: '奈良', role: 'sub', active: true, displayOrder: 38 },
  { name: '和歌山', role: 'sub', active: true, displayOrder: 39 },
  { name: '鳥取', role: 'sub', active: true, displayOrder: 40 },
  { name: '島根', role: 'sub', active: true, displayOrder: 41 },
  { name: '岡山', role: 'sub', active: true, displayOrder: 42 },
  { name: '広島', role: 'sub', active: true, displayOrder: 43 },
  { name: '山口', role: 'sub', active: true, displayOrder: 44 },
  { name: '徳島', role: 'sub', active: true, displayOrder: 45 },
  { name: '香川', role: 'sub', active: true, displayOrder: 46 },
  { name: '愛媛', role: 'sub', active: true, displayOrder: 47 },
  { name: '高知', role: 'sub', active: true, displayOrder: 48 },
  { name: '福岡', role: 'sub', active: true, displayOrder: 49 },
  { name: '佐賀', role: 'sub', active: true, displayOrder: 50 },
  { name: '長崎', role: 'sub', active: true, displayOrder: 51 },
  { name: '熊本', role: 'sub', active: true, displayOrder: 52 },
  { name: '大分', role: 'sub', active: true, displayOrder: 53 },
  { name: '宮崎', role: 'sub', active: true, displayOrder: 54 },
  { name: '鹿児島', role: 'sub', active: true, displayOrder: 55 },
  { name: '沖縄', role: 'sub', active: true, displayOrder: 56 },
  { name: '旭川', role: 'sub', active: true, displayOrder: 57 },
  { name: '多摩', role: 'sub', active: true, displayOrder: 58 },
  { name: '豊橋', role: 'sub', active: true, displayOrder: 59 },
  { name: '南大阪', role: 'sub', active: true, displayOrder: 60 },
  { name: '北九州', role: 'sub', active: true, displayOrder: 61 },
  
  // 支部 (3組織, displayOrder: 62-64)
  { name: '幕張', role: 'branch', active: true, displayOrder: 62 },
  { name: '所沢', role: 'branch', active: true, displayOrder: 63 },
  { name: '吉備', role: 'branch', active: true, displayOrder: 64 }
];